### PR TITLE
Wdio4 compatible

### PR DESCRIPTION
**Pull request by kevinlambert**
@christian-bromann I've created a gulp-webdriver webdriverio 4.0 compatible version.

It's written in ES6. 

The Webdriverio is installed as a peer dependency so that other webdriverio plugins can find it.

### CODE REVIEW

**Comment by jonyet** [comment]
@kevinlambert this error has been throwing since my update to v4 using gulp-webdriver

> webdriverio/build/lib/utils/ReporterStats.js:246
>             if (!specStats.suites[suiteTitle]) throw Error('Unrecognised suite [' + suiteTitle + '] for runner [' + specStats.specHash + ']');
>                                                ^
> Error: Unrecognised suite [] for runner [4cad33f7a110fb0c89ba1a0a0f058751]

i saw this before any work was done to update gulp-webdriver (or  my scripts) to work with wdio v4 - it prevented the specs from ever running. now that i've pulled this, everything works great but this error is still thrown at the tail end of the script run.

**Comment by christian-bromann** [comment]
@kevinlambert good job, I would be happy to merge this.
@jonyet wondering if anyone else gets this error

**Comment by jonyet** [comment]
anyone attempted to use this yet besides me? still seeing this error and unsure why. if either ofy ou have insight please let me know! :)

**Comment by christian-bromann** [comment]
Thanks @kevinlambert

**Pull request merged**
